some_app/urls.py
from django.urls import path
from .views import ProjectListView, ProjectUpdateView

urlpatterns = [
    path('', ProjectListView.as_view(), name='project_list'),
    path('projects/edit/<int:pk>/', ProjectUpdateView.as_view(), name='project_edit'),
]

some_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('some_app.urls')),
]

some_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Project(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    AbstractUser

    def __str__(self):
        return self.name

some_app/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, UpdateView
from .models import Project


class ProjectListView(PermissionRequiredMixin, ListView):
    model = Project
    template_name = 'project_list.html'
    context_object_name = 'projects'
    permission_required = 'some_app.view_project'


class ProjectUpdateView(PermissionRequiredMixin, UpdateView):
    model = Project
    fields = ['name', 'description', 'start_date', 'end_date']
    template_name = 'project_edit.html'
    permission_required = 'some_app.edit_project'

    def get_success_url(self):
        return reverse_lazy('project_list')

templates/project_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Редагування проекту</title>
</head>
<body>
    <h1>Редагування проекту</h1>

    <!-- Перевірка, чи користувач має дозвіл на редагування -->
    {% if perms.some_app.can_edit_Project %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}

            <button type="submit">Зберегти зміни</button>
        </form>
    {% else %}
        <p>У вас немає дозволу на редагування цього проекту.</p>
    {% endif %}

    <a href="{% url 'project_list' %}">Повернутися до списку проектів</a>
</body>
</html>

templates/project_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Project List</title>
</head>
<body>
    <h1>Projects</h1>
    <ul>
        {% for project in projects %}
            <li>
                <strong>{{ project.name }}</strong><br>
                {{ project.description }}<br>
                Дата початку: {{ project.start_date }}<br>
                Дата закінчення: {{ project.end_date }}

                <!-- Перевірка дозволу на редагування -->
                {% if perms.some_app.change_project %}
                    <a href="{% url 'project_edit' project.id %}">Редагувати</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>

    <!-- Відображення повідомлення, якщо у користувача немає дозволу на перегляд -->
    {% if not projects %}
        <p>Вам недоступні проекти для перегляду.</p>
    {% endif %}
</body>
</html>